name: gui_prototype
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:

  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.1.7  # Ensure this is the latest version
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/launcher_icon.png"